## Upraveno pro Flask-OS Demo
FROM python:3.10.13-bookworm
ENV APP=/app
RUN mkdir $APP
WORKDIR $APP
EXPOSE 8000
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
CMD ["gunicorn", "run:app", "--bind", "0.0.0.0:8000"]
